version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"

  server1:
    build:
      context: ./
    container_name: server1
    expose:
      - "8000"

  server2:
    build:
      context: ./
    container_name: server2
    expose:
      - "8000"
